#!/bin/sh


total="$(df -Bg | grep /nvme0n1p6 | awk '{ print $2 }')"
used="$(df -Bg | grep /nvme0n1p6 | awk '{ print $4 }')"

free=$(expr $total - $used)

if [ "$1" = "total" ]; then
    echo $total
elif [ "$1" = "used" ]; then
    echo $used
elif [ "$1" = "free" ]; then
    echo $free
fi
