#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor HDMI-A-0 -d  A B C D E
#bspc monitor eDP -d  F G H I J
bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           5
bspc config split_ratio          0.5
bspc config top_padding          30
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Mice bindings
#   Set mouse 1 to move floating windows
bspc config pointer_action1 move

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a 'VirtualBox Manager' state=floating

~/.fehbg
udiskie -t &
picom &
wname LG3D&

#Bar
~/.config/polybar/launch.sh &

