#!/bin/sh
workspaces() {

# Al camibiar esto deja de ir.
ws1="A"
ws2="B"
ws3="C"
ws4="D"
ws5="E"
ws6="F"
ws7="G"
ws8="H"
ws9="I"
ws0="J"

# Unoccupied
un="U"

# check if Occupied
o1=$(bspc query -D -d .occupied --names | grep "$ws1" )
o2=$(bspc query -D -d .occupied --names | grep "$ws2" )
o3=$(bspc query -D -d .occupied --names | grep "$ws3" )
o4=$(bspc query -D -d .occupied --names | grep "$ws4" )
o5=$(bspc query -D -d .occupied --names | grep "$ws5" )
o6=$(bspc query -D -d .occupied --names | grep "$ws6" )
o7=$(bspc query -D -d .occupied --names | grep "$ws7" )
o8=$(bspc query -D -d .occupied --names | grep "$ws8" )
o9=$(bspc query -D -d .occupied --names | grep "$ws9" )
o0=$(bspc query -D -d .occupied --names | grep "$ws0" )

# check if Focused
f1=$(bspc query -D -d focused --names | grep "$ws1" | tr "A" "a")
f2=$(bspc query -D -d focused --names | grep "$ws2" | tr "B" "b")
f3=$(bspc query -D -d focused --names | grep "$ws3" | tr "C" "c")
f4=$(bspc query -D -d focused --names | grep "$ws4" | tr "D" "d")
f5=$(bspc query -D -d focused --names | grep "$ws5" | tr "E" "e")
f6=$(bspc query -D -d focused --names | grep "$ws6" | tr "F" "f")
f7=$(bspc query -D -d focused --names | grep "$ws7" | tr "G" "g")
f8=$(bspc query -D -d focused --names | grep "$ws8" | tr "H" "h")
f9=$(bspc query -D -d focused --names | grep "$ws9" | tr "I" "i")
f0=$(bspc query -D -d focused --names | grep "$ws0" | tr "J" "j")

ic_1="_"
ic_2="_"
ic_3="_"
ic_4="_"
ic_5="_"
ic_6="_"
ic_7="_"
ic_8="_"
ic_9="_"
ic_0="_"
if [ $f1 ]; then
    ic_1="_"
elif [ $f2 ]; then
    ic_2="_"
elif [ $f3 ]; then
    ic_3="_"
elif [ $f4 ]; then
    ic_4="_"
elif [ $f5 ]; then
    ic_5="_"
elif [ $f6 ]; then
    ic_6="_"
elif [ $f7 ]; then
    ic_7="_"
elif [ $f8 ]; then
    ic_8="_"
elif [ $f9 ]; then
    ic_9="_"
elif [ $f0 ]; then
    ic_0="_"
fi

# No tocar, mientras intantaba cambiar cosas en esta linea se jodió. Creo que es solo si añades cambios de linea pero por si acaso xd.
echo 	"(box	:class \"works\"	:orientation \"h\" :spacing 5 :space-evenly \"false\" (button :onclick \"bspc desktop -f $ws1\"	:class	\"$un$o1$f1\"	\"$ic_1\") (button :onclick \"bspc desktop -f $ws2\"	:class \"$un$o2$f2\"	 \"$ic_2\") (button :onclick \"bspc desktop -f $ws3\"	:class \"$un$o3$f3\" \"$ic_3\") (button :onclick \"bspc desktop -f $ws4\"	:class \"$un$o4$f4\"	\"$ic_4\") (button :onclick \"bspc desktop -f $ws5\"	:class \"$un$o5$f5\" \"$ic_5\") (button :onclick \"bspc desktop -f $ws6\"	:class \"$un$o6$f6\" \"$ic_6\") (button :onclick \"bspc desktop -f $ws7\"	:class \"$un$o7$f7\" \"$ic_7\") (button :onclick \"bspc desktop -f $ws8\"	:class \"$un$o8$f8\" \"$ic_8\") (button :onclick \"bspc desktop -f $ws9\"	:class \"$un$o9$f9\" \"$ic_9\") (button :onclick \"bspc desktop -f $ws0\"	:class \"$un$o0$f0\" \"$ic_0\"))"

}
workspaces
bspc subscribe desktop node_transfer | while read -r _ ; do
workspaces
done
