#!/bin/bash

function send_notification() {
	volume=$(amixer get Master | tail -n 1 | awk {'print($5)'} | cut -d '[' -f2 | cut -d '%' -f1)
	dunstify -a "changevolume" -u low -r "9993" -h int:value:"$volume" -i "volume-$1" "Volume: ${volume}%" -t 1000
}

case $1 in
up)
	# Set the volume on (if it was muted)
	amixer set Master unmute
	amixer set Master 5%+
  send_notification $1
	;;
down)
	amixer set Master unmute
	amixer set Master 5%-
	send_notification $1
	;;
mute)
	amixer set Master toggle
  volume_status=$(amixer get Master | tail -n 1 | awk {'print($6)'} | cut -d '[' -f2 | cut -d ']' -f1)
	if [[ $volume_status == 'off' ]]; then
		dunstify -i volume-mute -a "changevolume" -t 2000 -r 9993 -u low "Muted"
	else
		send_notification up
	fi
	;;
esac
